FROM node:20-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

FROM node:20-alpine
WORKDIR /app
COPY --from=build /app/dist/TaskManagerUI/server ./server
COPY --from=build /app/dist/TaskManagerUI/browser ./browser
EXPOSE 4000
CMD ["node", "server/server.mjs"]